# Generated by Django 2.2.4 on 2019-08-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mobiles',
            new_name='Desktop',
        ),
        migrations.RenameModel(
            old_name='Desktops',
            new_name='Laptop',
        ),
        migrations.RenameModel(
            old_name='Laptops',
            new_name='Mobile',
        ),
    ]
